export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CONTRACTS_REQUEST = "CONTRACTS_REQUEST";
export const CONTRACTS_SUCCESS = "CONTRACTS_SUCCESS";
export const CONTRACTS_FAILURE = "CONTRACTS_FAILURE";
